Total number of unique barcodes:             20000
TN - Total number of fragments:              682771111
UM - Total number of uniquely mapped:        574811249
SE - Total number of single ends:            10278875
SA - Total number of secondary alignments:   0
PE - Total number of paired ends:            564532374
PP - Total number of proper paired:          560473650
PL - Total number of proper frag len:        429759107
US - Total number of usable fragments:       429759107
UQ - Total number of unique fragments:       282287469
CM - Total number of chrM fragments:         244846
